$base = "C:\Users\USER-PC\Downloads\stitch_artisan_marketplace_hub"

$mapping = @{
    "Browse Gallery - Artisane Buy Art"                          = "browse-gallery.html"
    "Commissions - Artisane Gallery"                             = "commissions.html"
    "Artisane Home - Curated Marketplace"                        = "index.html"
    "Your Commissions - Artisane Gallery"                        = "user-commissions.html"
    "Artist Portfolio - Elena Vance (Updated)"                   = "artist-portfolio-updated.html"
    "Artisane Journal - Editorial Stories"                       = "journal.html"
    "Request Received - Artisane Gallery"                        = "request-received.html"
    "Become an Artisane Artist"                                  = "become-artist.html"
    "Auction Registration Overview - Artisane Gallery"           = "auction-registration.html"
    "Auction History - Artisane Gallery"                         = "auction-history.html"
    "Artist Profile - Elena Vance"                               = "artist-profile.html"
    "Registration Successful - Artisane Gallery"                 = "registration-successful.html"
    "Artists Directory - Discover Creators"                      = "artists.html"
    "Bidder Verification - Identity Setup"                       = "verification.html"
    "Curation Review - Artist Applications"                      = "curation-review.html"
    "Browse Gallery - Artisane (Light Theme)"                    = "browse-gallery-light.html"
    "Live Bidding - Ethereal Tides"                              = "live-bidding.html"
    "Payment Pre-authorization - Auction Registration"           = "payment-preauth.html"
    "Artist Profile - Elena Vance (Mobile)"                      = "artist-profile-mobile.html"
    "Artisane Home - Light Gallery (Primary)"                    = "home-light.html"
    "Certificate of Authenticity - Visions of the Inland Sea"  
<truncated 3527 bytes>